language: c
script: dpkg-buildpackage -uc -us
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --no-install-recommends -qq asciidoc xsltproc xmlto lynx check libevent-dev libpurple-dev
 - wget http://dump.dequis.org/indexed/bitlbee-travis-libs/libotr5{,-dev}_4.1.0-2~bpo70+1_amd64.deb
 - sudo dpkg -i *.deb

